require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LabClassesController do

  # This should return the minimal set of attributes required to create a valid
  # LabClass. As you add validations to LabClass, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LabClassesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lab_classes as @lab_classes" do
      lab_class = LabClass.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lab_classes).should eq([lab_class])
    end
  end

  describe "GET show" do
    it "assigns the requested lab_class as @lab_class" do
      lab_class = LabClass.create! valid_attributes
      get :show, {:id => lab_class.to_param}, valid_session
      assigns(:lab_class).should eq(lab_class)
    end
  end

  describe "GET new" do
    it "assigns a new lab_class as @lab_class" do
      get :new, {}, valid_session
      assigns(:lab_class).should be_a_new(LabClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested lab_class as @lab_class" do
      lab_class = LabClass.create! valid_attributes
      get :edit, {:id => lab_class.to_param}, valid_session
      assigns(:lab_class).should eq(lab_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LabClass" do
        expect {
          post :create, {:lab_class => valid_attributes}, valid_session
        }.to change(LabClass, :count).by(1)
      end

      it "assigns a newly created lab_class as @lab_class" do
        post :create, {:lab_class => valid_attributes}, valid_session
        assigns(:lab_class).should be_a(LabClass)
        assigns(:lab_class).should be_persisted
      end

      it "redirects to the created lab_class" do
        post :create, {:lab_class => valid_attributes}, valid_session
        response.should redirect_to(LabClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lab_class as @lab_class" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabClass.any_instance.stub(:save).and_return(false)
        post :create, {:lab_class => {}}, valid_session
        assigns(:lab_class).should be_a_new(LabClass)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LabClass.any_instance.stub(:save).and_return(false)
        post :create, {:lab_class => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lab_class" do
        lab_class = LabClass.create! valid_attributes
        # Assuming there are no other lab_classes in the database, this
        # specifies that the LabClass created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LabClass.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lab_class.to_param, :lab_class => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lab_class as @lab_class" do
        lab_class = LabClass.create! valid_attributes
        put :update, {:id => lab_class.to_param, :lab_class => valid_attributes}, valid_session
        assigns(:lab_class).should eq(lab_class)
      end

      it "redirects to the lab_class" do
        lab_class = LabClass.create! valid_attributes
        put :update, {:id => lab_class.to_param, :lab_class => valid_attributes}, valid_session
        response.should redirect_to(lab_class)
      end
    end

    describe "with invalid params" do
      it "assigns the lab_class as @lab_class" do
        lab_class = LabClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => lab_class.to_param, :lab_class => {}}, valid_session
        assigns(:lab_class).should eq(lab_class)
      end

      it "re-renders the 'edit' template" do
        lab_class = LabClass.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LabClass.any_instance.stub(:save).and_return(false)
        put :update, {:id => lab_class.to_param, :lab_class => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lab_class" do
      lab_class = LabClass.create! valid_attributes
      expect {
        delete :destroy, {:id => lab_class.to_param}, valid_session
      }.to change(LabClass, :count).by(-1)
    end

    it "redirects to the lab_classes list" do
      lab_class = LabClass.create! valid_attributes
      delete :destroy, {:id => lab_class.to_param}, valid_session
      response.should redirect_to(lab_classes_url)
    end
  end

end
